services:
  backend:
    image: ghcr.io/get-convex/convex-backend:latest
    ports:
      - '3210:3210' # Main API
      - '3211:3211' # HTTP Actions
    volumes:
      - convex_data:/convex/data
    environment:
      - CONVEX_RELEASE_VERSION_DEV=true
      - RUST_LOG=info
    restart: always

  dashboard:
    image: ghcr.io/get-convex/convex-dashboard:latest
    ports:
      - '8085:6791'
    environment:
      - CONVEX_BACKEND_URL=http://localhost:3210
    restart: always

volumes:
  convex_data:
