/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as ProfileCompleteImport } from './routes/profileComplete'
import { Route as HomeImport } from './routes/home'
import { Route as AboutImport } from './routes/about'
import { Route as IndexImport } from './routes/index'
import { Route as HomeVendorsImport } from './routes/home/vendors'
import { Route as HomeTakeOrderImport } from './routes/home/takeOrder'
import { Route as HomeStockImport } from './routes/home/stock'
import { Route as HomeNotificationsImport } from './routes/home/notifications'
import { Route as HomeMenuManagementImport } from './routes/home/menuManagement'
import { Route as HomeInventoryManagementImport } from './routes/home/inventoryManagement'
import { Route as HomeInventoryHistoryImport } from './routes/home/inventoryHistory'
import { Route as HomeEmployeeImport } from './routes/home/employee'
import { Route as HomeDashboardImport } from './routes/home/dashboard'
import { Route as HomeCreditorsImport } from './routes/home/creditors'
import { Route as HomeVendorsNicknameImport } from './routes/home/vendors/$nickname'
import { Route as HomeNotificationsStockNotificationImport } from './routes/home/notifications/stockNotification'
import { Route as HomeNotificationsOrderNotificationImport } from './routes/home/notifications/orderNotification'
import { Route as HomeEmployeeTableImport } from './routes/home/employee/table'
import { Route as HomeEmployeeEmployeeDailyReportImport } from './routes/home/employee/employeeDailyReport'
import { Route as HomeEmployeeSalaryLedgerImport } from './routes/home/employee/$salaryLedger'
import { Route as HomeCreditorsCreditorsAllImport } from './routes/home/creditors/creditorsAll'
import { Route as HomeCreditorsNicknameImport } from './routes/home/creditors/$nickname'
import { Route as HomeEmployeeEmployeeDailyReportEmployeeIdImport } from './routes/home/employee/employeeDailyReport/$employeeId'
import { Route as HomeEmployeeEmployeeIdSalesImport } from './routes/home/employee/$employeeId/sales'

// Create Virtual Routes

const HomeUtilityLedgerLazyImport = createFileRoute('/home/utilityLedger')()
const HomeSettingsLazyImport = createFileRoute('/home/settings')()
const HomePermanentInventoryLazyImport = createFileRoute(
  '/home/permanentInventory',
)()
const HomeKitchenLedgerLazyImport = createFileRoute('/home/kitchenLedger')()
const HomeHelpLazyImport = createFileRoute('/home/help')()
const HomeGeneralExpenseTrackerLazyImport = createFileRoute(
  '/home/generalExpenseTracker',
)()
const HomeEquipmentLazyImport = createFileRoute('/home/equipment')()
const HomeCalendarLazyImport = createFileRoute('/home/calendar')()
const HomeBillingLazyImport = createFileRoute('/home/billing')()
const HomeBaristaLedgerLazyImport = createFileRoute('/home/baristaLedger')()
const HomeBakeryLedgerLazyImport = createFileRoute('/home/bakeryLedger')()

// Create/Update Routes

const ProfileCompleteRoute = ProfileCompleteImport.update({
  id: '/profileComplete',
  path: '/profileComplete',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/profileComplete.lazy').then((d) => d.Route),
)

const HomeRoute = HomeImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRoute,
} as any)

const AboutRoute = AboutImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const HomeUtilityLedgerLazyRoute = HomeUtilityLedgerLazyImport.update({
  id: '/utilityLedger',
  path: '/utilityLedger',
  getParentRoute: () => HomeRoute,
} as any).lazy(() =>
  import('./routes/home/utilityLedger.lazy').then((d) => d.Route),
)

const HomeSettingsLazyRoute = HomeSettingsLazyImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => HomeRoute,
} as any).lazy(() => import('./routes/home/settings.lazy').then((d) => d.Route))

const HomePermanentInventoryLazyRoute = HomePermanentInventoryLazyImport.update(
  {
    id: '/permanentInventory',
    path: '/permanentInventory',
    getParentRoute: () => HomeRoute,
  } as any,
).lazy(() =>
  import('./routes/home/permanentInventory.lazy').then((d) => d.Route),
)

const HomeKitchenLedgerLazyRoute = HomeKitchenLedgerLazyImport.update({
  id: '/kitchenLedger',
  path: '/kitchenLedger',
  getParentRoute: () => HomeRoute,
} as any).lazy(() =>
  import('./routes/home/kitchenLedger.lazy').then((d) => d.Route),
)

const HomeHelpLazyRoute = HomeHelpLazyImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => HomeRoute,
} as any).lazy(() => import('./routes/home/help.lazy').then((d) => d.Route))

const HomeGeneralExpenseTrackerLazyRoute =
  HomeGeneralExpenseTrackerLazyImport.update({
    id: '/generalExpenseTracker',
    path: '/generalExpenseTracker',
    getParentRoute: () => HomeRoute,
  } as any).lazy(() =>
    import('./routes/home/generalExpenseTracker.lazy').then((d) => d.Route),
  )

const HomeEquipmentLazyRoute = HomeEquipmentLazyImport.update({
  id: '/equipment',
  path: '/equipment',
  getParentRoute: () => HomeRoute,
} as any).lazy(() =>
  import('./routes/home/equipment.lazy').then((d) => d.Route),
)

const HomeCalendarLazyRoute = HomeCalendarLazyImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => HomeRoute,
} as any).lazy(() => import('./routes/home/calendar.lazy').then((d) => d.Route))

const HomeBillingLazyRoute = HomeBillingLazyImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => HomeRoute,
} as any).lazy(() => import('./routes/home/billing.lazy').then((d) => d.Route))

const HomeBaristaLedgerLazyRoute = HomeBaristaLedgerLazyImport.update({
  id: '/baristaLedger',
  path: '/baristaLedger',
  getParentRoute: () => HomeRoute,
} as any).lazy(() =>
  import('./routes/home/baristaLedger.lazy').then((d) => d.Route),
)

const HomeBakeryLedgerLazyRoute = HomeBakeryLedgerLazyImport.update({
  id: '/bakeryLedger',
  path: '/bakeryLedger',
  getParentRoute: () => HomeRoute,
} as any).lazy(() =>
  import('./routes/home/bakeryLedger.lazy').then((d) => d.Route),
)

const HomeVendorsRoute = HomeVendorsImport.update({
  id: '/vendors',
  path: '/vendors',
  getParentRoute: () => HomeRoute,
} as any)

const HomeTakeOrderRoute = HomeTakeOrderImport.update({
  id: '/takeOrder',
  path: '/takeOrder',
  getParentRoute: () => HomeRoute,
} as any)

const HomeStockRoute = HomeStockImport.update({
  id: '/stock',
  path: '/stock',
  getParentRoute: () => HomeRoute,
} as any).lazy(() => import('./routes/home/stock.lazy').then((d) => d.Route))

const HomeNotificationsRoute = HomeNotificationsImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => HomeRoute,
} as any)

const HomeMenuManagementRoute = HomeMenuManagementImport.update({
  id: '/menuManagement',
  path: '/menuManagement',
  getParentRoute: () => HomeRoute,
} as any)

const HomeInventoryManagementRoute = HomeInventoryManagementImport.update({
  id: '/inventoryManagement',
  path: '/inventoryManagement',
  getParentRoute: () => HomeRoute,
} as any)

const HomeInventoryHistoryRoute = HomeInventoryHistoryImport.update({
  id: '/inventoryHistory',
  path: '/inventoryHistory',
  getParentRoute: () => HomeRoute,
} as any)

const HomeEmployeeRoute = HomeEmployeeImport.update({
  id: '/employee',
  path: '/employee',
  getParentRoute: () => HomeRoute,
} as any)

const HomeDashboardRoute = HomeDashboardImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => HomeRoute,
} as any).lazy(() =>
  import('./routes/home/dashboard.lazy').then((d) => d.Route),
)

const HomeCreditorsRoute = HomeCreditorsImport.update({
  id: '/creditors',
  path: '/creditors',
  getParentRoute: () => HomeRoute,
} as any)

const HomeVendorsNicknameRoute = HomeVendorsNicknameImport.update({
  id: '/$nickname',
  path: '/$nickname',
  getParentRoute: () => HomeVendorsRoute,
} as any)

const HomeNotificationsStockNotificationRoute =
  HomeNotificationsStockNotificationImport.update({
    id: '/stockNotification',
    path: '/stockNotification',
    getParentRoute: () => HomeNotificationsRoute,
  } as any)

const HomeNotificationsOrderNotificationRoute =
  HomeNotificationsOrderNotificationImport.update({
    id: '/orderNotification',
    path: '/orderNotification',
    getParentRoute: () => HomeNotificationsRoute,
  } as any)

const HomeEmployeeTableRoute = HomeEmployeeTableImport.update({
  id: '/table',
  path: '/table',
  getParentRoute: () => HomeEmployeeRoute,
} as any).lazy(() =>
  import('./routes/home/employee/table.lazy').then((d) => d.Route),
)

const HomeEmployeeEmployeeDailyReportRoute =
  HomeEmployeeEmployeeDailyReportImport.update({
    id: '/employeeDailyReport',
    path: '/employeeDailyReport',
    getParentRoute: () => HomeEmployeeRoute,
  } as any)

const HomeEmployeeSalaryLedgerRoute = HomeEmployeeSalaryLedgerImport.update({
  id: '/$salaryLedger',
  path: '/$salaryLedger',
  getParentRoute: () => HomeEmployeeRoute,
} as any)

const HomeCreditorsCreditorsAllRoute = HomeCreditorsCreditorsAllImport.update({
  id: '/creditorsAll',
  path: '/creditorsAll',
  getParentRoute: () => HomeCreditorsRoute,
} as any)

const HomeCreditorsNicknameRoute = HomeCreditorsNicknameImport.update({
  id: '/$nickname',
  path: '/$nickname',
  getParentRoute: () => HomeCreditorsRoute,
} as any)

const HomeEmployeeEmployeeDailyReportEmployeeIdRoute =
  HomeEmployeeEmployeeDailyReportEmployeeIdImport.update({
    id: '/$employeeId',
    path: '/$employeeId',
    getParentRoute: () => HomeEmployeeEmployeeDailyReportRoute,
  } as any)

const HomeEmployeeEmployeeIdSalesRoute =
  HomeEmployeeEmployeeIdSalesImport.update({
    id: '/$employeeId/sales',
    path: '/$employeeId/sales',
    getParentRoute: () => HomeEmployeeRoute,
  } as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutImport
      parentRoute: typeof rootRoute
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeImport
      parentRoute: typeof rootRoute
    }
    '/profileComplete': {
      id: '/profileComplete'
      path: '/profileComplete'
      fullPath: '/profileComplete'
      preLoaderRoute: typeof ProfileCompleteImport
      parentRoute: typeof rootRoute
    }
    '/home/creditors': {
      id: '/home/creditors'
      path: '/creditors'
      fullPath: '/home/creditors'
      preLoaderRoute: typeof HomeCreditorsImport
      parentRoute: typeof HomeImport
    }
    '/home/dashboard': {
      id: '/home/dashboard'
      path: '/dashboard'
      fullPath: '/home/dashboard'
      preLoaderRoute: typeof HomeDashboardImport
      parentRoute: typeof HomeImport
    }
    '/home/employee': {
      id: '/home/employee'
      path: '/employee'
      fullPath: '/home/employee'
      preLoaderRoute: typeof HomeEmployeeImport
      parentRoute: typeof HomeImport
    }
    '/home/inventoryHistory': {
      id: '/home/inventoryHistory'
      path: '/inventoryHistory'
      fullPath: '/home/inventoryHistory'
      preLoaderRoute: typeof HomeInventoryHistoryImport
      parentRoute: typeof HomeImport
    }
    '/home/inventoryManagement': {
      id: '/home/inventoryManagement'
      path: '/inventoryManagement'
      fullPath: '/home/inventoryManagement'
      preLoaderRoute: typeof HomeInventoryManagementImport
      parentRoute: typeof HomeImport
    }
    '/home/menuManagement': {
      id: '/home/menuManagement'
      path: '/menuManagement'
      fullPath: '/home/menuManagement'
      preLoaderRoute: typeof HomeMenuManagementImport
      parentRoute: typeof HomeImport
    }
    '/home/notifications': {
      id: '/home/notifications'
      path: '/notifications'
      fullPath: '/home/notifications'
      preLoaderRoute: typeof HomeNotificationsImport
      parentRoute: typeof HomeImport
    }
    '/home/stock': {
      id: '/home/stock'
      path: '/stock'
      fullPath: '/home/stock'
      preLoaderRoute: typeof HomeStockImport
      parentRoute: typeof HomeImport
    }
    '/home/takeOrder': {
      id: '/home/takeOrder'
      path: '/takeOrder'
      fullPath: '/home/takeOrder'
      preLoaderRoute: typeof HomeTakeOrderImport
      parentRoute: typeof HomeImport
    }
    '/home/vendors': {
      id: '/home/vendors'
      path: '/vendors'
      fullPath: '/home/vendors'
      preLoaderRoute: typeof HomeVendorsImport
      parentRoute: typeof HomeImport
    }
    '/home/bakeryLedger': {
      id: '/home/bakeryLedger'
      path: '/bakeryLedger'
      fullPath: '/home/bakeryLedger'
      preLoaderRoute: typeof HomeBakeryLedgerLazyImport
      parentRoute: typeof HomeImport
    }
    '/home/baristaLedger': {
      id: '/home/baristaLedger'
      path: '/baristaLedger'
      fullPath: '/home/baristaLedger'
      preLoaderRoute: typeof HomeBaristaLedgerLazyImport
      parentRoute: typeof HomeImport
    }
    '/home/billing': {
      id: '/home/billing'
      path: '/billing'
      fullPath: '/home/billing'
      preLoaderRoute: typeof HomeBillingLazyImport
      parentRoute: typeof HomeImport
    }
    '/home/calendar': {
      id: '/home/calendar'
      path: '/calendar'
      fullPath: '/home/calendar'
      preLoaderRoute: typeof HomeCalendarLazyImport
      parentRoute: typeof HomeImport
    }
    '/home/equipment': {
      id: '/home/equipment'
      path: '/equipment'
      fullPath: '/home/equipment'
      preLoaderRoute: typeof HomeEquipmentLazyImport
      parentRoute: typeof HomeImport
    }
    '/home/generalExpenseTracker': {
      id: '/home/generalExpenseTracker'
      path: '/generalExpenseTracker'
      fullPath: '/home/generalExpenseTracker'
      preLoaderRoute: typeof HomeGeneralExpenseTrackerLazyImport
      parentRoute: typeof HomeImport
    }
    '/home/help': {
      id: '/home/help'
      path: '/help'
      fullPath: '/home/help'
      preLoaderRoute: typeof HomeHelpLazyImport
      parentRoute: typeof HomeImport
    }
    '/home/kitchenLedger': {
      id: '/home/kitchenLedger'
      path: '/kitchenLedger'
      fullPath: '/home/kitchenLedger'
      preLoaderRoute: typeof HomeKitchenLedgerLazyImport
      parentRoute: typeof HomeImport
    }
    '/home/permanentInventory': {
      id: '/home/permanentInventory'
      path: '/permanentInventory'
      fullPath: '/home/permanentInventory'
      preLoaderRoute: typeof HomePermanentInventoryLazyImport
      parentRoute: typeof HomeImport
    }
    '/home/settings': {
      id: '/home/settings'
      path: '/settings'
      fullPath: '/home/settings'
      preLoaderRoute: typeof HomeSettingsLazyImport
      parentRoute: typeof HomeImport
    }
    '/home/utilityLedger': {
      id: '/home/utilityLedger'
      path: '/utilityLedger'
      fullPath: '/home/utilityLedger'
      preLoaderRoute: typeof HomeUtilityLedgerLazyImport
      parentRoute: typeof HomeImport
    }
    '/home/creditors/$nickname': {
      id: '/home/creditors/$nickname'
      path: '/$nickname'
      fullPath: '/home/creditors/$nickname'
      preLoaderRoute: typeof HomeCreditorsNicknameImport
      parentRoute: typeof HomeCreditorsImport
    }
    '/home/creditors/creditorsAll': {
      id: '/home/creditors/creditorsAll'
      path: '/creditorsAll'
      fullPath: '/home/creditors/creditorsAll'
      preLoaderRoute: typeof HomeCreditorsCreditorsAllImport
      parentRoute: typeof HomeCreditorsImport
    }
    '/home/employee/$salaryLedger': {
      id: '/home/employee/$salaryLedger'
      path: '/$salaryLedger'
      fullPath: '/home/employee/$salaryLedger'
      preLoaderRoute: typeof HomeEmployeeSalaryLedgerImport
      parentRoute: typeof HomeEmployeeImport
    }
    '/home/employee/employeeDailyReport': {
      id: '/home/employee/employeeDailyReport'
      path: '/employeeDailyReport'
      fullPath: '/home/employee/employeeDailyReport'
      preLoaderRoute: typeof HomeEmployeeEmployeeDailyReportImport
      parentRoute: typeof HomeEmployeeImport
    }
    '/home/employee/table': {
      id: '/home/employee/table'
      path: '/table'
      fullPath: '/home/employee/table'
      preLoaderRoute: typeof HomeEmployeeTableImport
      parentRoute: typeof HomeEmployeeImport
    }
    '/home/notifications/orderNotification': {
      id: '/home/notifications/orderNotification'
      path: '/orderNotification'
      fullPath: '/home/notifications/orderNotification'
      preLoaderRoute: typeof HomeNotificationsOrderNotificationImport
      parentRoute: typeof HomeNotificationsImport
    }
    '/home/notifications/stockNotification': {
      id: '/home/notifications/stockNotification'
      path: '/stockNotification'
      fullPath: '/home/notifications/stockNotification'
      preLoaderRoute: typeof HomeNotificationsStockNotificationImport
      parentRoute: typeof HomeNotificationsImport
    }
    '/home/vendors/$nickname': {
      id: '/home/vendors/$nickname'
      path: '/$nickname'
      fullPath: '/home/vendors/$nickname'
      preLoaderRoute: typeof HomeVendorsNicknameImport
      parentRoute: typeof HomeVendorsImport
    }
    '/home/employee/$employeeId/sales': {
      id: '/home/employee/$employeeId/sales'
      path: '/$employeeId/sales'
      fullPath: '/home/employee/$employeeId/sales'
      preLoaderRoute: typeof HomeEmployeeEmployeeIdSalesImport
      parentRoute: typeof HomeEmployeeImport
    }
    '/home/employee/employeeDailyReport/$employeeId': {
      id: '/home/employee/employeeDailyReport/$employeeId'
      path: '/$employeeId'
      fullPath: '/home/employee/employeeDailyReport/$employeeId'
      preLoaderRoute: typeof HomeEmployeeEmployeeDailyReportEmployeeIdImport
      parentRoute: typeof HomeEmployeeEmployeeDailyReportImport
    }
  }
}

// Create and export the route tree

interface HomeCreditorsRouteChildren {
  HomeCreditorsNicknameRoute: typeof HomeCreditorsNicknameRoute
  HomeCreditorsCreditorsAllRoute: typeof HomeCreditorsCreditorsAllRoute
}

const HomeCreditorsRouteChildren: HomeCreditorsRouteChildren = {
  HomeCreditorsNicknameRoute: HomeCreditorsNicknameRoute,
  HomeCreditorsCreditorsAllRoute: HomeCreditorsCreditorsAllRoute,
}

const HomeCreditorsRouteWithChildren = HomeCreditorsRoute._addFileChildren(
  HomeCreditorsRouteChildren,
)

interface HomeEmployeeEmployeeDailyReportRouteChildren {
  HomeEmployeeEmployeeDailyReportEmployeeIdRoute: typeof HomeEmployeeEmployeeDailyReportEmployeeIdRoute
}

const HomeEmployeeEmployeeDailyReportRouteChildren: HomeEmployeeEmployeeDailyReportRouteChildren =
  {
    HomeEmployeeEmployeeDailyReportEmployeeIdRoute:
      HomeEmployeeEmployeeDailyReportEmployeeIdRoute,
  }

const HomeEmployeeEmployeeDailyReportRouteWithChildren =
  HomeEmployeeEmployeeDailyReportRoute._addFileChildren(
    HomeEmployeeEmployeeDailyReportRouteChildren,
  )

interface HomeEmployeeRouteChildren {
  HomeEmployeeSalaryLedgerRoute: typeof HomeEmployeeSalaryLedgerRoute
  HomeEmployeeEmployeeDailyReportRoute: typeof HomeEmployeeEmployeeDailyReportRouteWithChildren
  HomeEmployeeTableRoute: typeof HomeEmployeeTableRoute
  HomeEmployeeEmployeeIdSalesRoute: typeof HomeEmployeeEmployeeIdSalesRoute
}

const HomeEmployeeRouteChildren: HomeEmployeeRouteChildren = {
  HomeEmployeeSalaryLedgerRoute: HomeEmployeeSalaryLedgerRoute,
  HomeEmployeeEmployeeDailyReportRoute:
    HomeEmployeeEmployeeDailyReportRouteWithChildren,
  HomeEmployeeTableRoute: HomeEmployeeTableRoute,
  HomeEmployeeEmployeeIdSalesRoute: HomeEmployeeEmployeeIdSalesRoute,
}

const HomeEmployeeRouteWithChildren = HomeEmployeeRoute._addFileChildren(
  HomeEmployeeRouteChildren,
)

interface HomeNotificationsRouteChildren {
  HomeNotificationsOrderNotificationRoute: typeof HomeNotificationsOrderNotificationRoute
  HomeNotificationsStockNotificationRoute: typeof HomeNotificationsStockNotificationRoute
}

const HomeNotificationsRouteChildren: HomeNotificationsRouteChildren = {
  HomeNotificationsOrderNotificationRoute:
    HomeNotificationsOrderNotificationRoute,
  HomeNotificationsStockNotificationRoute:
    HomeNotificationsStockNotificationRoute,
}

const HomeNotificationsRouteWithChildren =
  HomeNotificationsRoute._addFileChildren(HomeNotificationsRouteChildren)

interface HomeVendorsRouteChildren {
  HomeVendorsNicknameRoute: typeof HomeVendorsNicknameRoute
}

const HomeVendorsRouteChildren: HomeVendorsRouteChildren = {
  HomeVendorsNicknameRoute: HomeVendorsNicknameRoute,
}

const HomeVendorsRouteWithChildren = HomeVendorsRoute._addFileChildren(
  HomeVendorsRouteChildren,
)

interface HomeRouteChildren {
  HomeCreditorsRoute: typeof HomeCreditorsRouteWithChildren
  HomeDashboardRoute: typeof HomeDashboardRoute
  HomeEmployeeRoute: typeof HomeEmployeeRouteWithChildren
  HomeInventoryHistoryRoute: typeof HomeInventoryHistoryRoute
  HomeInventoryManagementRoute: typeof HomeInventoryManagementRoute
  HomeMenuManagementRoute: typeof HomeMenuManagementRoute
  HomeNotificationsRoute: typeof HomeNotificationsRouteWithChildren
  HomeStockRoute: typeof HomeStockRoute
  HomeTakeOrderRoute: typeof HomeTakeOrderRoute
  HomeVendorsRoute: typeof HomeVendorsRouteWithChildren
  HomeBakeryLedgerLazyRoute: typeof HomeBakeryLedgerLazyRoute
  HomeBaristaLedgerLazyRoute: typeof HomeBaristaLedgerLazyRoute
  HomeBillingLazyRoute: typeof HomeBillingLazyRoute
  HomeCalendarLazyRoute: typeof HomeCalendarLazyRoute
  HomeEquipmentLazyRoute: typeof HomeEquipmentLazyRoute
  HomeGeneralExpenseTrackerLazyRoute: typeof HomeGeneralExpenseTrackerLazyRoute
  HomeHelpLazyRoute: typeof HomeHelpLazyRoute
  HomeKitchenLedgerLazyRoute: typeof HomeKitchenLedgerLazyRoute
  HomePermanentInventoryLazyRoute: typeof HomePermanentInventoryLazyRoute
  HomeSettingsLazyRoute: typeof HomeSettingsLazyRoute
  HomeUtilityLedgerLazyRoute: typeof HomeUtilityLedgerLazyRoute
}

const HomeRouteChildren: HomeRouteChildren = {
  HomeCreditorsRoute: HomeCreditorsRouteWithChildren,
  HomeDashboardRoute: HomeDashboardRoute,
  HomeEmployeeRoute: HomeEmployeeRouteWithChildren,
  HomeInventoryHistoryRoute: HomeInventoryHistoryRoute,
  HomeInventoryManagementRoute: HomeInventoryManagementRoute,
  HomeMenuManagementRoute: HomeMenuManagementRoute,
  HomeNotificationsRoute: HomeNotificationsRouteWithChildren,
  HomeStockRoute: HomeStockRoute,
  HomeTakeOrderRoute: HomeTakeOrderRoute,
  HomeVendorsRoute: HomeVendorsRouteWithChildren,
  HomeBakeryLedgerLazyRoute: HomeBakeryLedgerLazyRoute,
  HomeBaristaLedgerLazyRoute: HomeBaristaLedgerLazyRoute,
  HomeBillingLazyRoute: HomeBillingLazyRoute,
  HomeCalendarLazyRoute: HomeCalendarLazyRoute,
  HomeEquipmentLazyRoute: HomeEquipmentLazyRoute,
  HomeGeneralExpenseTrackerLazyRoute: HomeGeneralExpenseTrackerLazyRoute,
  HomeHelpLazyRoute: HomeHelpLazyRoute,
  HomeKitchenLedgerLazyRoute: HomeKitchenLedgerLazyRoute,
  HomePermanentInventoryLazyRoute: HomePermanentInventoryLazyRoute,
  HomeSettingsLazyRoute: HomeSettingsLazyRoute,
  HomeUtilityLedgerLazyRoute: HomeUtilityLedgerLazyRoute,
}

const HomeRouteWithChildren = HomeRoute._addFileChildren(HomeRouteChildren)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/home': typeof HomeRouteWithChildren
  '/profileComplete': typeof ProfileCompleteRoute
  '/home/creditors': typeof HomeCreditorsRouteWithChildren
  '/home/dashboard': typeof HomeDashboardRoute
  '/home/employee': typeof HomeEmployeeRouteWithChildren
  '/home/inventoryHistory': typeof HomeInventoryHistoryRoute
  '/home/inventoryManagement': typeof HomeInventoryManagementRoute
  '/home/menuManagement': typeof HomeMenuManagementRoute
  '/home/notifications': typeof HomeNotificationsRouteWithChildren
  '/home/stock': typeof HomeStockRoute
  '/home/takeOrder': typeof HomeTakeOrderRoute
  '/home/vendors': typeof HomeVendorsRouteWithChildren
  '/home/bakeryLedger': typeof HomeBakeryLedgerLazyRoute
  '/home/baristaLedger': typeof HomeBaristaLedgerLazyRoute
  '/home/billing': typeof HomeBillingLazyRoute
  '/home/calendar': typeof HomeCalendarLazyRoute
  '/home/equipment': typeof HomeEquipmentLazyRoute
  '/home/generalExpenseTracker': typeof HomeGeneralExpenseTrackerLazyRoute
  '/home/help': typeof HomeHelpLazyRoute
  '/home/kitchenLedger': typeof HomeKitchenLedgerLazyRoute
  '/home/permanentInventory': typeof HomePermanentInventoryLazyRoute
  '/home/settings': typeof HomeSettingsLazyRoute
  '/home/utilityLedger': typeof HomeUtilityLedgerLazyRoute
  '/home/creditors/$nickname': typeof HomeCreditorsNicknameRoute
  '/home/creditors/creditorsAll': typeof HomeCreditorsCreditorsAllRoute
  '/home/employee/$salaryLedger': typeof HomeEmployeeSalaryLedgerRoute
  '/home/employee/employeeDailyReport': typeof HomeEmployeeEmployeeDailyReportRouteWithChildren
  '/home/employee/table': typeof HomeEmployeeTableRoute
  '/home/notifications/orderNotification': typeof HomeNotificationsOrderNotificationRoute
  '/home/notifications/stockNotification': typeof HomeNotificationsStockNotificationRoute
  '/home/vendors/$nickname': typeof HomeVendorsNicknameRoute
  '/home/employee/$employeeId/sales': typeof HomeEmployeeEmployeeIdSalesRoute
  '/home/employee/employeeDailyReport/$employeeId': typeof HomeEmployeeEmployeeDailyReportEmployeeIdRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/home': typeof HomeRouteWithChildren
  '/profileComplete': typeof ProfileCompleteRoute
  '/home/creditors': typeof HomeCreditorsRouteWithChildren
  '/home/dashboard': typeof HomeDashboardRoute
  '/home/employee': typeof HomeEmployeeRouteWithChildren
  '/home/inventoryHistory': typeof HomeInventoryHistoryRoute
  '/home/inventoryManagement': typeof HomeInventoryManagementRoute
  '/home/menuManagement': typeof HomeMenuManagementRoute
  '/home/notifications': typeof HomeNotificationsRouteWithChildren
  '/home/stock': typeof HomeStockRoute
  '/home/takeOrder': typeof HomeTakeOrderRoute
  '/home/vendors': typeof HomeVendorsRouteWithChildren
  '/home/bakeryLedger': typeof HomeBakeryLedgerLazyRoute
  '/home/baristaLedger': typeof HomeBaristaLedgerLazyRoute
  '/home/billing': typeof HomeBillingLazyRoute
  '/home/calendar': typeof HomeCalendarLazyRoute
  '/home/equipment': typeof HomeEquipmentLazyRoute
  '/home/generalExpenseTracker': typeof HomeGeneralExpenseTrackerLazyRoute
  '/home/help': typeof HomeHelpLazyRoute
  '/home/kitchenLedger': typeof HomeKitchenLedgerLazyRoute
  '/home/permanentInventory': typeof HomePermanentInventoryLazyRoute
  '/home/settings': typeof HomeSettingsLazyRoute
  '/home/utilityLedger': typeof HomeUtilityLedgerLazyRoute
  '/home/creditors/$nickname': typeof HomeCreditorsNicknameRoute
  '/home/creditors/creditorsAll': typeof HomeCreditorsCreditorsAllRoute
  '/home/employee/$salaryLedger': typeof HomeEmployeeSalaryLedgerRoute
  '/home/employee/employeeDailyReport': typeof HomeEmployeeEmployeeDailyReportRouteWithChildren
  '/home/employee/table': typeof HomeEmployeeTableRoute
  '/home/notifications/orderNotification': typeof HomeNotificationsOrderNotificationRoute
  '/home/notifications/stockNotification': typeof HomeNotificationsStockNotificationRoute
  '/home/vendors/$nickname': typeof HomeVendorsNicknameRoute
  '/home/employee/$employeeId/sales': typeof HomeEmployeeEmployeeIdSalesRoute
  '/home/employee/employeeDailyReport/$employeeId': typeof HomeEmployeeEmployeeDailyReportEmployeeIdRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/home': typeof HomeRouteWithChildren
  '/profileComplete': typeof ProfileCompleteRoute
  '/home/creditors': typeof HomeCreditorsRouteWithChildren
  '/home/dashboard': typeof HomeDashboardRoute
  '/home/employee': typeof HomeEmployeeRouteWithChildren
  '/home/inventoryHistory': typeof HomeInventoryHistoryRoute
  '/home/inventoryManagement': typeof HomeInventoryManagementRoute
  '/home/menuManagement': typeof HomeMenuManagementRoute
  '/home/notifications': typeof HomeNotificationsRouteWithChildren
  '/home/stock': typeof HomeStockRoute
  '/home/takeOrder': typeof HomeTakeOrderRoute
  '/home/vendors': typeof HomeVendorsRouteWithChildren
  '/home/bakeryLedger': typeof HomeBakeryLedgerLazyRoute
  '/home/baristaLedger': typeof HomeBaristaLedgerLazyRoute
  '/home/billing': typeof HomeBillingLazyRoute
  '/home/calendar': typeof HomeCalendarLazyRoute
  '/home/equipment': typeof HomeEquipmentLazyRoute
  '/home/generalExpenseTracker': typeof HomeGeneralExpenseTrackerLazyRoute
  '/home/help': typeof HomeHelpLazyRoute
  '/home/kitchenLedger': typeof HomeKitchenLedgerLazyRoute
  '/home/permanentInventory': typeof HomePermanentInventoryLazyRoute
  '/home/settings': typeof HomeSettingsLazyRoute
  '/home/utilityLedger': typeof HomeUtilityLedgerLazyRoute
  '/home/creditors/$nickname': typeof HomeCreditorsNicknameRoute
  '/home/creditors/creditorsAll': typeof HomeCreditorsCreditorsAllRoute
  '/home/employee/$salaryLedger': typeof HomeEmployeeSalaryLedgerRoute
  '/home/employee/employeeDailyReport': typeof HomeEmployeeEmployeeDailyReportRouteWithChildren
  '/home/employee/table': typeof HomeEmployeeTableRoute
  '/home/notifications/orderNotification': typeof HomeNotificationsOrderNotificationRoute
  '/home/notifications/stockNotification': typeof HomeNotificationsStockNotificationRoute
  '/home/vendors/$nickname': typeof HomeVendorsNicknameRoute
  '/home/employee/$employeeId/sales': typeof HomeEmployeeEmployeeIdSalesRoute
  '/home/employee/employeeDailyReport/$employeeId': typeof HomeEmployeeEmployeeDailyReportEmployeeIdRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/home'
    | '/profileComplete'
    | '/home/creditors'
    | '/home/dashboard'
    | '/home/employee'
    | '/home/inventoryHistory'
    | '/home/inventoryManagement'
    | '/home/menuManagement'
    | '/home/notifications'
    | '/home/stock'
    | '/home/takeOrder'
    | '/home/vendors'
    | '/home/bakeryLedger'
    | '/home/baristaLedger'
    | '/home/billing'
    | '/home/calendar'
    | '/home/equipment'
    | '/home/generalExpenseTracker'
    | '/home/help'
    | '/home/kitchenLedger'
    | '/home/permanentInventory'
    | '/home/settings'
    | '/home/utilityLedger'
    | '/home/creditors/$nickname'
    | '/home/creditors/creditorsAll'
    | '/home/employee/$salaryLedger'
    | '/home/employee/employeeDailyReport'
    | '/home/employee/table'
    | '/home/notifications/orderNotification'
    | '/home/notifications/stockNotification'
    | '/home/vendors/$nickname'
    | '/home/employee/$employeeId/sales'
    | '/home/employee/employeeDailyReport/$employeeId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/home'
    | '/profileComplete'
    | '/home/creditors'
    | '/home/dashboard'
    | '/home/employee'
    | '/home/inventoryHistory'
    | '/home/inventoryManagement'
    | '/home/menuManagement'
    | '/home/notifications'
    | '/home/stock'
    | '/home/takeOrder'
    | '/home/vendors'
    | '/home/bakeryLedger'
    | '/home/baristaLedger'
    | '/home/billing'
    | '/home/calendar'
    | '/home/equipment'
    | '/home/generalExpenseTracker'
    | '/home/help'
    | '/home/kitchenLedger'
    | '/home/permanentInventory'
    | '/home/settings'
    | '/home/utilityLedger'
    | '/home/creditors/$nickname'
    | '/home/creditors/creditorsAll'
    | '/home/employee/$salaryLedger'
    | '/home/employee/employeeDailyReport'
    | '/home/employee/table'
    | '/home/notifications/orderNotification'
    | '/home/notifications/stockNotification'
    | '/home/vendors/$nickname'
    | '/home/employee/$employeeId/sales'
    | '/home/employee/employeeDailyReport/$employeeId'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/home'
    | '/profileComplete'
    | '/home/creditors'
    | '/home/dashboard'
    | '/home/employee'
    | '/home/inventoryHistory'
    | '/home/inventoryManagement'
    | '/home/menuManagement'
    | '/home/notifications'
    | '/home/stock'
    | '/home/takeOrder'
    | '/home/vendors'
    | '/home/bakeryLedger'
    | '/home/baristaLedger'
    | '/home/billing'
    | '/home/calendar'
    | '/home/equipment'
    | '/home/generalExpenseTracker'
    | '/home/help'
    | '/home/kitchenLedger'
    | '/home/permanentInventory'
    | '/home/settings'
    | '/home/utilityLedger'
    | '/home/creditors/$nickname'
    | '/home/creditors/creditorsAll'
    | '/home/employee/$salaryLedger'
    | '/home/employee/employeeDailyReport'
    | '/home/employee/table'
    | '/home/notifications/orderNotification'
    | '/home/notifications/stockNotification'
    | '/home/vendors/$nickname'
    | '/home/employee/$employeeId/sales'
    | '/home/employee/employeeDailyReport/$employeeId'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  HomeRoute: typeof HomeRouteWithChildren
  ProfileCompleteRoute: typeof ProfileCompleteRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  HomeRoute: HomeRouteWithChildren,
  ProfileCompleteRoute: ProfileCompleteRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/about",
        "/home",
        "/profileComplete"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/about": {
      "filePath": "about.tsx"
    },
    "/home": {
      "filePath": "home.tsx",
      "children": [
        "/home/creditors",
        "/home/dashboard",
        "/home/employee",
        "/home/inventoryHistory",
        "/home/inventoryManagement",
        "/home/menuManagement",
        "/home/notifications",
        "/home/stock",
        "/home/takeOrder",
        "/home/vendors",
        "/home/bakeryLedger",
        "/home/baristaLedger",
        "/home/billing",
        "/home/calendar",
        "/home/equipment",
        "/home/generalExpenseTracker",
        "/home/help",
        "/home/kitchenLedger",
        "/home/permanentInventory",
        "/home/settings",
        "/home/utilityLedger"
      ]
    },
    "/profileComplete": {
      "filePath": "profileComplete.tsx"
    },
    "/home/creditors": {
      "filePath": "home/creditors.tsx",
      "parent": "/home",
      "children": [
        "/home/creditors/$nickname",
        "/home/creditors/creditorsAll"
      ]
    },
    "/home/dashboard": {
      "filePath": "home/dashboard.tsx",
      "parent": "/home"
    },
    "/home/employee": {
      "filePath": "home/employee.tsx",
      "parent": "/home",
      "children": [
        "/home/employee/$salaryLedger",
        "/home/employee/employeeDailyReport",
        "/home/employee/table",
        "/home/employee/$employeeId/sales"
      ]
    },
    "/home/inventoryHistory": {
      "filePath": "home/inventoryHistory.tsx",
      "parent": "/home"
    },
    "/home/inventoryManagement": {
      "filePath": "home/inventoryManagement.tsx",
      "parent": "/home"
    },
    "/home/menuManagement": {
      "filePath": "home/menuManagement.tsx",
      "parent": "/home"
    },
    "/home/notifications": {
      "filePath": "home/notifications.tsx",
      "parent": "/home",
      "children": [
        "/home/notifications/orderNotification",
        "/home/notifications/stockNotification"
      ]
    },
    "/home/stock": {
      "filePath": "home/stock.tsx",
      "parent": "/home"
    },
    "/home/takeOrder": {
      "filePath": "home/takeOrder.tsx",
      "parent": "/home"
    },
    "/home/vendors": {
      "filePath": "home/vendors.tsx",
      "parent": "/home",
      "children": [
        "/home/vendors/$nickname"
      ]
    },
    "/home/bakeryLedger": {
      "filePath": "home/bakeryLedger.lazy.tsx",
      "parent": "/home"
    },
    "/home/baristaLedger": {
      "filePath": "home/baristaLedger.lazy.tsx",
      "parent": "/home"
    },
    "/home/billing": {
      "filePath": "home/billing.lazy.tsx",
      "parent": "/home"
    },
    "/home/calendar": {
      "filePath": "home/calendar.lazy.tsx",
      "parent": "/home"
    },
    "/home/equipment": {
      "filePath": "home/equipment.lazy.tsx",
      "parent": "/home"
    },
    "/home/generalExpenseTracker": {
      "filePath": "home/generalExpenseTracker.lazy.tsx",
      "parent": "/home"
    },
    "/home/help": {
      "filePath": "home/help.lazy.tsx",
      "parent": "/home"
    },
    "/home/kitchenLedger": {
      "filePath": "home/kitchenLedger.lazy.tsx",
      "parent": "/home"
    },
    "/home/permanentInventory": {
      "filePath": "home/permanentInventory.lazy.tsx",
      "parent": "/home"
    },
    "/home/settings": {
      "filePath": "home/settings.lazy.tsx",
      "parent": "/home"
    },
    "/home/utilityLedger": {
      "filePath": "home/utilityLedger.lazy.tsx",
      "parent": "/home"
    },
    "/home/creditors/$nickname": {
      "filePath": "home/creditors/$nickname.tsx",
      "parent": "/home/creditors"
    },
    "/home/creditors/creditorsAll": {
      "filePath": "home/creditors/creditorsAll.tsx",
      "parent": "/home/creditors"
    },
    "/home/employee/$salaryLedger": {
      "filePath": "home/employee/$salaryLedger.tsx",
      "parent": "/home/employee"
    },
    "/home/employee/employeeDailyReport": {
      "filePath": "home/employee/employeeDailyReport.tsx",
      "parent": "/home/employee",
      "children": [
        "/home/employee/employeeDailyReport/$employeeId"
      ]
    },
    "/home/employee/table": {
      "filePath": "home/employee/table.tsx",
      "parent": "/home/employee"
    },
    "/home/notifications/orderNotification": {
      "filePath": "home/notifications/orderNotification.tsx",
      "parent": "/home/notifications"
    },
    "/home/notifications/stockNotification": {
      "filePath": "home/notifications/stockNotification.tsx",
      "parent": "/home/notifications"
    },
    "/home/vendors/$nickname": {
      "filePath": "home/vendors/$nickname.tsx",
      "parent": "/home/vendors"
    },
    "/home/employee/$employeeId/sales": {
      "filePath": "home/employee/$employeeId/sales.tsx",
      "parent": "/home/employee"
    },
    "/home/employee/employeeDailyReport/$employeeId": {
      "filePath": "home/employee/employeeDailyReport/$employeeId.tsx",
      "parent": "/home/employee/employeeDailyReport"
    }
  }
}
ROUTE_MANIFEST_END */
