/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as UnverifiedImport } from './routes/unverified'
import { Route as HomeImport } from './routes/home'
import { Route as IndexImport } from './routes/index'
import { Route as HomeVendorsImport } from './routes/home/vendors'
import { Route as HomeTakeOrderImport } from './routes/home/takeOrder'
import { Route as HomePayLaterCustomersImport } from './routes/home/payLaterCustomers'
import { Route as HomeNotificationsImport } from './routes/home/notifications'
import { Route as HomeMenuManagementImport } from './routes/home/menuManagement'
import { Route as HomeInventoryManagementImport } from './routes/home/inventoryManagement'
import { Route as HomeInventoryHistoryImport } from './routes/home/inventoryHistory'
import { Route as HomeEmployeeImport } from './routes/home/employee'
import { Route as HomeDashboardImport } from './routes/home/dashboard'
import { Route as HomeExpenseLedgerRouteImport } from './routes/home/expenseLedger/route'
import { Route as HomeAssetsRouteImport } from './routes/home/assets/route'
import { Route as HomeVendorsVendorsAllImport } from './routes/home/vendors/vendorsAll'
import { Route as HomeVendorsIdImport } from './routes/home/vendors/$id'
import { Route as HomePayLaterCustomersPayLaterCustomersAllImport } from './routes/home/payLaterCustomers/payLaterCustomersAll'
import { Route as HomePayLaterCustomersIdImport } from './routes/home/payLaterCustomers/$id'
import { Route as HomeNotificationsOrderNotificationImport } from './routes/home/notifications/orderNotification'
import { Route as HomeExpenseLedgerDepartmentImport } from './routes/home/expenseLedger/$department'
import { Route as HomeEmployeeTableImport } from './routes/home/employee/table'
import { Route as HomeEmployeeEmployeeDailyReportImport } from './routes/home/employee/employeeDailyReport'
import { Route as HomeEmployeeSalaryLedgerImport } from './routes/home/employee/$salaryLedger'
import { Route as HomeAssetsDepartmentImport } from './routes/home/assets/$department'
import { Route as HomeEmployeeEmployeeDailyReportEmployeeIdImport } from './routes/home/employee/employeeDailyReport/$employeeId'

// Create Virtual Routes

const PrinterConfigLazyImport = createFileRoute('/printerConfig')()
const HomeSettingsLazyImport = createFileRoute('/home/settings')()
const HomePrinterConfigLazyImport = createFileRoute('/home/printerConfig')()
const HomeHelpLazyImport = createFileRoute('/home/help')()
const HomeConfigurationsLazyImport = createFileRoute('/home/configurations')()
const HomeCalendarLazyImport = createFileRoute('/home/calendar')()
const HomeBillingLazyImport = createFileRoute('/home/billing')()

// Create/Update Routes

const PrinterConfigLazyRoute = PrinterConfigLazyImport.update({
  id: '/printerConfig',
  path: '/printerConfig',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/printerConfig.lazy').then((d) => d.Route))

const UnverifiedRoute = UnverifiedImport.update({
  id: '/unverified',
  path: '/unverified',
  getParentRoute: () => rootRoute,
} as any)

const HomeRoute = HomeImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const HomeSettingsLazyRoute = HomeSettingsLazyImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => HomeRoute,
} as any).lazy(() => import('./routes/home/settings.lazy').then((d) => d.Route))

const HomePrinterConfigLazyRoute = HomePrinterConfigLazyImport.update({
  id: '/printerConfig',
  path: '/printerConfig',
  getParentRoute: () => HomeRoute,
} as any).lazy(() =>
  import('./routes/home/printerConfig.lazy').then((d) => d.Route),
)

const HomeHelpLazyRoute = HomeHelpLazyImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => HomeRoute,
} as any).lazy(() => import('./routes/home/help.lazy').then((d) => d.Route))

const HomeConfigurationsLazyRoute = HomeConfigurationsLazyImport.update({
  id: '/configurations',
  path: '/configurations',
  getParentRoute: () => HomeRoute,
} as any).lazy(() =>
  import('./routes/home/configurations.lazy').then((d) => d.Route),
)

const HomeCalendarLazyRoute = HomeCalendarLazyImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => HomeRoute,
} as any).lazy(() => import('./routes/home/calendar.lazy').then((d) => d.Route))

const HomeBillingLazyRoute = HomeBillingLazyImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => HomeRoute,
} as any).lazy(() => import('./routes/home/billing.lazy').then((d) => d.Route))

const HomeVendorsRoute = HomeVendorsImport.update({
  id: '/vendors',
  path: '/vendors',
  getParentRoute: () => HomeRoute,
} as any)

const HomeTakeOrderRoute = HomeTakeOrderImport.update({
  id: '/takeOrder',
  path: '/takeOrder',
  getParentRoute: () => HomeRoute,
} as any)

const HomePayLaterCustomersRoute = HomePayLaterCustomersImport.update({
  id: '/payLaterCustomers',
  path: '/payLaterCustomers',
  getParentRoute: () => HomeRoute,
} as any)

const HomeNotificationsRoute = HomeNotificationsImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => HomeRoute,
} as any)

const HomeMenuManagementRoute = HomeMenuManagementImport.update({
  id: '/menuManagement',
  path: '/menuManagement',
  getParentRoute: () => HomeRoute,
} as any)

const HomeInventoryManagementRoute = HomeInventoryManagementImport.update({
  id: '/inventoryManagement',
  path: '/inventoryManagement',
  getParentRoute: () => HomeRoute,
} as any)

const HomeInventoryHistoryRoute = HomeInventoryHistoryImport.update({
  id: '/inventoryHistory',
  path: '/inventoryHistory',
  getParentRoute: () => HomeRoute,
} as any)

const HomeEmployeeRoute = HomeEmployeeImport.update({
  id: '/employee',
  path: '/employee',
  getParentRoute: () => HomeRoute,
} as any)

const HomeDashboardRoute = HomeDashboardImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => HomeRoute,
} as any).lazy(() =>
  import('./routes/home/dashboard.lazy').then((d) => d.Route),
)

const HomeExpenseLedgerRouteRoute = HomeExpenseLedgerRouteImport.update({
  id: '/expenseLedger',
  path: '/expenseLedger',
  getParentRoute: () => HomeRoute,
} as any)

const HomeAssetsRouteRoute = HomeAssetsRouteImport.update({
  id: '/assets',
  path: '/assets',
  getParentRoute: () => HomeRoute,
} as any)

const HomeVendorsVendorsAllRoute = HomeVendorsVendorsAllImport.update({
  id: '/vendorsAll',
  path: '/vendorsAll',
  getParentRoute: () => HomeVendorsRoute,
} as any)

const HomeVendorsIdRoute = HomeVendorsIdImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => HomeVendorsRoute,
} as any)

const HomePayLaterCustomersPayLaterCustomersAllRoute =
  HomePayLaterCustomersPayLaterCustomersAllImport.update({
    id: '/payLaterCustomersAll',
    path: '/payLaterCustomersAll',
    getParentRoute: () => HomePayLaterCustomersRoute,
  } as any)

const HomePayLaterCustomersIdRoute = HomePayLaterCustomersIdImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => HomePayLaterCustomersRoute,
} as any)

const HomeNotificationsOrderNotificationRoute =
  HomeNotificationsOrderNotificationImport.update({
    id: '/orderNotification',
    path: '/orderNotification',
    getParentRoute: () => HomeNotificationsRoute,
  } as any)

const HomeExpenseLedgerDepartmentRoute =
  HomeExpenseLedgerDepartmentImport.update({
    id: '/$department',
    path: '/$department',
    getParentRoute: () => HomeExpenseLedgerRouteRoute,
  } as any)

const HomeEmployeeTableRoute = HomeEmployeeTableImport.update({
  id: '/table',
  path: '/table',
  getParentRoute: () => HomeEmployeeRoute,
} as any).lazy(() =>
  import('./routes/home/employee/table.lazy').then((d) => d.Route),
)

const HomeEmployeeEmployeeDailyReportRoute =
  HomeEmployeeEmployeeDailyReportImport.update({
    id: '/employeeDailyReport',
    path: '/employeeDailyReport',
    getParentRoute: () => HomeEmployeeRoute,
  } as any)

const HomeEmployeeSalaryLedgerRoute = HomeEmployeeSalaryLedgerImport.update({
  id: '/$salaryLedger',
  path: '/$salaryLedger',
  getParentRoute: () => HomeEmployeeRoute,
} as any)

const HomeAssetsDepartmentRoute = HomeAssetsDepartmentImport.update({
  id: '/$department',
  path: '/$department',
  getParentRoute: () => HomeAssetsRouteRoute,
} as any)

const HomeEmployeeEmployeeDailyReportEmployeeIdRoute =
  HomeEmployeeEmployeeDailyReportEmployeeIdImport.update({
    id: '/$employeeId',
    path: '/$employeeId',
    getParentRoute: () => HomeEmployeeEmployeeDailyReportRoute,
  } as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeImport
      parentRoute: typeof rootRoute
    }
    '/unverified': {
      id: '/unverified'
      path: '/unverified'
      fullPath: '/unverified'
      preLoaderRoute: typeof UnverifiedImport
      parentRoute: typeof rootRoute
    }
    '/printerConfig': {
      id: '/printerConfig'
      path: '/printerConfig'
      fullPath: '/printerConfig'
      preLoaderRoute: typeof PrinterConfigLazyImport
      parentRoute: typeof rootRoute
    }
    '/home/assets': {
      id: '/home/assets'
      path: '/assets'
      fullPath: '/home/assets'
      preLoaderRoute: typeof HomeAssetsRouteImport
      parentRoute: typeof HomeImport
    }
    '/home/expenseLedger': {
      id: '/home/expenseLedger'
      path: '/expenseLedger'
      fullPath: '/home/expenseLedger'
      preLoaderRoute: typeof HomeExpenseLedgerRouteImport
      parentRoute: typeof HomeImport
    }
    '/home/dashboard': {
      id: '/home/dashboard'
      path: '/dashboard'
      fullPath: '/home/dashboard'
      preLoaderRoute: typeof HomeDashboardImport
      parentRoute: typeof HomeImport
    }
    '/home/employee': {
      id: '/home/employee'
      path: '/employee'
      fullPath: '/home/employee'
      preLoaderRoute: typeof HomeEmployeeImport
      parentRoute: typeof HomeImport
    }
    '/home/inventoryHistory': {
      id: '/home/inventoryHistory'
      path: '/inventoryHistory'
      fullPath: '/home/inventoryHistory'
      preLoaderRoute: typeof HomeInventoryHistoryImport
      parentRoute: typeof HomeImport
    }
    '/home/inventoryManagement': {
      id: '/home/inventoryManagement'
      path: '/inventoryManagement'
      fullPath: '/home/inventoryManagement'
      preLoaderRoute: typeof HomeInventoryManagementImport
      parentRoute: typeof HomeImport
    }
    '/home/menuManagement': {
      id: '/home/menuManagement'
      path: '/menuManagement'
      fullPath: '/home/menuManagement'
      preLoaderRoute: typeof HomeMenuManagementImport
      parentRoute: typeof HomeImport
    }
    '/home/notifications': {
      id: '/home/notifications'
      path: '/notifications'
      fullPath: '/home/notifications'
      preLoaderRoute: typeof HomeNotificationsImport
      parentRoute: typeof HomeImport
    }
    '/home/payLaterCustomers': {
      id: '/home/payLaterCustomers'
      path: '/payLaterCustomers'
      fullPath: '/home/payLaterCustomers'
      preLoaderRoute: typeof HomePayLaterCustomersImport
      parentRoute: typeof HomeImport
    }
    '/home/takeOrder': {
      id: '/home/takeOrder'
      path: '/takeOrder'
      fullPath: '/home/takeOrder'
      preLoaderRoute: typeof HomeTakeOrderImport
      parentRoute: typeof HomeImport
    }
    '/home/vendors': {
      id: '/home/vendors'
      path: '/vendors'
      fullPath: '/home/vendors'
      preLoaderRoute: typeof HomeVendorsImport
      parentRoute: typeof HomeImport
    }
    '/home/billing': {
      id: '/home/billing'
      path: '/billing'
      fullPath: '/home/billing'
      preLoaderRoute: typeof HomeBillingLazyImport
      parentRoute: typeof HomeImport
    }
    '/home/calendar': {
      id: '/home/calendar'
      path: '/calendar'
      fullPath: '/home/calendar'
      preLoaderRoute: typeof HomeCalendarLazyImport
      parentRoute: typeof HomeImport
    }
    '/home/configurations': {
      id: '/home/configurations'
      path: '/configurations'
      fullPath: '/home/configurations'
      preLoaderRoute: typeof HomeConfigurationsLazyImport
      parentRoute: typeof HomeImport
    }
    '/home/help': {
      id: '/home/help'
      path: '/help'
      fullPath: '/home/help'
      preLoaderRoute: typeof HomeHelpLazyImport
      parentRoute: typeof HomeImport
    }
    '/home/printerConfig': {
      id: '/home/printerConfig'
      path: '/printerConfig'
      fullPath: '/home/printerConfig'
      preLoaderRoute: typeof HomePrinterConfigLazyImport
      parentRoute: typeof HomeImport
    }
    '/home/settings': {
      id: '/home/settings'
      path: '/settings'
      fullPath: '/home/settings'
      preLoaderRoute: typeof HomeSettingsLazyImport
      parentRoute: typeof HomeImport
    }
    '/home/assets/$department': {
      id: '/home/assets/$department'
      path: '/$department'
      fullPath: '/home/assets/$department'
      preLoaderRoute: typeof HomeAssetsDepartmentImport
      parentRoute: typeof HomeAssetsRouteImport
    }
    '/home/employee/$salaryLedger': {
      id: '/home/employee/$salaryLedger'
      path: '/$salaryLedger'
      fullPath: '/home/employee/$salaryLedger'
      preLoaderRoute: typeof HomeEmployeeSalaryLedgerImport
      parentRoute: typeof HomeEmployeeImport
    }
    '/home/employee/employeeDailyReport': {
      id: '/home/employee/employeeDailyReport'
      path: '/employeeDailyReport'
      fullPath: '/home/employee/employeeDailyReport'
      preLoaderRoute: typeof HomeEmployeeEmployeeDailyReportImport
      parentRoute: typeof HomeEmployeeImport
    }
    '/home/employee/table': {
      id: '/home/employee/table'
      path: '/table'
      fullPath: '/home/employee/table'
      preLoaderRoute: typeof HomeEmployeeTableImport
      parentRoute: typeof HomeEmployeeImport
    }
    '/home/expenseLedger/$department': {
      id: '/home/expenseLedger/$department'
      path: '/$department'
      fullPath: '/home/expenseLedger/$department'
      preLoaderRoute: typeof HomeExpenseLedgerDepartmentImport
      parentRoute: typeof HomeExpenseLedgerRouteImport
    }
    '/home/notifications/orderNotification': {
      id: '/home/notifications/orderNotification'
      path: '/orderNotification'
      fullPath: '/home/notifications/orderNotification'
      preLoaderRoute: typeof HomeNotificationsOrderNotificationImport
      parentRoute: typeof HomeNotificationsImport
    }
    '/home/payLaterCustomers/$id': {
      id: '/home/payLaterCustomers/$id'
      path: '/$id'
      fullPath: '/home/payLaterCustomers/$id'
      preLoaderRoute: typeof HomePayLaterCustomersIdImport
      parentRoute: typeof HomePayLaterCustomersImport
    }
    '/home/payLaterCustomers/payLaterCustomersAll': {
      id: '/home/payLaterCustomers/payLaterCustomersAll'
      path: '/payLaterCustomersAll'
      fullPath: '/home/payLaterCustomers/payLaterCustomersAll'
      preLoaderRoute: typeof HomePayLaterCustomersPayLaterCustomersAllImport
      parentRoute: typeof HomePayLaterCustomersImport
    }
    '/home/vendors/$id': {
      id: '/home/vendors/$id'
      path: '/$id'
      fullPath: '/home/vendors/$id'
      preLoaderRoute: typeof HomeVendorsIdImport
      parentRoute: typeof HomeVendorsImport
    }
    '/home/vendors/vendorsAll': {
      id: '/home/vendors/vendorsAll'
      path: '/vendorsAll'
      fullPath: '/home/vendors/vendorsAll'
      preLoaderRoute: typeof HomeVendorsVendorsAllImport
      parentRoute: typeof HomeVendorsImport
    }
    '/home/employee/employeeDailyReport/$employeeId': {
      id: '/home/employee/employeeDailyReport/$employeeId'
      path: '/$employeeId'
      fullPath: '/home/employee/employeeDailyReport/$employeeId'
      preLoaderRoute: typeof HomeEmployeeEmployeeDailyReportEmployeeIdImport
      parentRoute: typeof HomeEmployeeEmployeeDailyReportImport
    }
  }
}

// Create and export the route tree

interface HomeAssetsRouteRouteChildren {
  HomeAssetsDepartmentRoute: typeof HomeAssetsDepartmentRoute
}

const HomeAssetsRouteRouteChildren: HomeAssetsRouteRouteChildren = {
  HomeAssetsDepartmentRoute: HomeAssetsDepartmentRoute,
}

const HomeAssetsRouteRouteWithChildren = HomeAssetsRouteRoute._addFileChildren(
  HomeAssetsRouteRouteChildren,
)

interface HomeExpenseLedgerRouteRouteChildren {
  HomeExpenseLedgerDepartmentRoute: typeof HomeExpenseLedgerDepartmentRoute
}

const HomeExpenseLedgerRouteRouteChildren: HomeExpenseLedgerRouteRouteChildren =
  {
    HomeExpenseLedgerDepartmentRoute: HomeExpenseLedgerDepartmentRoute,
  }

const HomeExpenseLedgerRouteRouteWithChildren =
  HomeExpenseLedgerRouteRoute._addFileChildren(
    HomeExpenseLedgerRouteRouteChildren,
  )

interface HomeEmployeeEmployeeDailyReportRouteChildren {
  HomeEmployeeEmployeeDailyReportEmployeeIdRoute: typeof HomeEmployeeEmployeeDailyReportEmployeeIdRoute
}

const HomeEmployeeEmployeeDailyReportRouteChildren: HomeEmployeeEmployeeDailyReportRouteChildren =
  {
    HomeEmployeeEmployeeDailyReportEmployeeIdRoute:
      HomeEmployeeEmployeeDailyReportEmployeeIdRoute,
  }

const HomeEmployeeEmployeeDailyReportRouteWithChildren =
  HomeEmployeeEmployeeDailyReportRoute._addFileChildren(
    HomeEmployeeEmployeeDailyReportRouteChildren,
  )

interface HomeEmployeeRouteChildren {
  HomeEmployeeSalaryLedgerRoute: typeof HomeEmployeeSalaryLedgerRoute
  HomeEmployeeEmployeeDailyReportRoute: typeof HomeEmployeeEmployeeDailyReportRouteWithChildren
  HomeEmployeeTableRoute: typeof HomeEmployeeTableRoute
}

const HomeEmployeeRouteChildren: HomeEmployeeRouteChildren = {
  HomeEmployeeSalaryLedgerRoute: HomeEmployeeSalaryLedgerRoute,
  HomeEmployeeEmployeeDailyReportRoute:
    HomeEmployeeEmployeeDailyReportRouteWithChildren,
  HomeEmployeeTableRoute: HomeEmployeeTableRoute,
}

const HomeEmployeeRouteWithChildren = HomeEmployeeRoute._addFileChildren(
  HomeEmployeeRouteChildren,
)

interface HomeNotificationsRouteChildren {
  HomeNotificationsOrderNotificationRoute: typeof HomeNotificationsOrderNotificationRoute
}

const HomeNotificationsRouteChildren: HomeNotificationsRouteChildren = {
  HomeNotificationsOrderNotificationRoute:
    HomeNotificationsOrderNotificationRoute,
}

const HomeNotificationsRouteWithChildren =
  HomeNotificationsRoute._addFileChildren(HomeNotificationsRouteChildren)

interface HomePayLaterCustomersRouteChildren {
  HomePayLaterCustomersIdRoute: typeof HomePayLaterCustomersIdRoute
  HomePayLaterCustomersPayLaterCustomersAllRoute: typeof HomePayLaterCustomersPayLaterCustomersAllRoute
}

const HomePayLaterCustomersRouteChildren: HomePayLaterCustomersRouteChildren = {
  HomePayLaterCustomersIdRoute: HomePayLaterCustomersIdRoute,
  HomePayLaterCustomersPayLaterCustomersAllRoute:
    HomePayLaterCustomersPayLaterCustomersAllRoute,
}

const HomePayLaterCustomersRouteWithChildren =
  HomePayLaterCustomersRoute._addFileChildren(
    HomePayLaterCustomersRouteChildren,
  )

interface HomeVendorsRouteChildren {
  HomeVendorsIdRoute: typeof HomeVendorsIdRoute
  HomeVendorsVendorsAllRoute: typeof HomeVendorsVendorsAllRoute
}

const HomeVendorsRouteChildren: HomeVendorsRouteChildren = {
  HomeVendorsIdRoute: HomeVendorsIdRoute,
  HomeVendorsVendorsAllRoute: HomeVendorsVendorsAllRoute,
}

const HomeVendorsRouteWithChildren = HomeVendorsRoute._addFileChildren(
  HomeVendorsRouteChildren,
)

interface HomeRouteChildren {
  HomeAssetsRouteRoute: typeof HomeAssetsRouteRouteWithChildren
  HomeExpenseLedgerRouteRoute: typeof HomeExpenseLedgerRouteRouteWithChildren
  HomeDashboardRoute: typeof HomeDashboardRoute
  HomeEmployeeRoute: typeof HomeEmployeeRouteWithChildren
  HomeInventoryHistoryRoute: typeof HomeInventoryHistoryRoute
  HomeInventoryManagementRoute: typeof HomeInventoryManagementRoute
  HomeMenuManagementRoute: typeof HomeMenuManagementRoute
  HomeNotificationsRoute: typeof HomeNotificationsRouteWithChildren
  HomePayLaterCustomersRoute: typeof HomePayLaterCustomersRouteWithChildren
  HomeTakeOrderRoute: typeof HomeTakeOrderRoute
  HomeVendorsRoute: typeof HomeVendorsRouteWithChildren
  HomeBillingLazyRoute: typeof HomeBillingLazyRoute
  HomeCalendarLazyRoute: typeof HomeCalendarLazyRoute
  HomeConfigurationsLazyRoute: typeof HomeConfigurationsLazyRoute
  HomeHelpLazyRoute: typeof HomeHelpLazyRoute
  HomePrinterConfigLazyRoute: typeof HomePrinterConfigLazyRoute
  HomeSettingsLazyRoute: typeof HomeSettingsLazyRoute
}

const HomeRouteChildren: HomeRouteChildren = {
  HomeAssetsRouteRoute: HomeAssetsRouteRouteWithChildren,
  HomeExpenseLedgerRouteRoute: HomeExpenseLedgerRouteRouteWithChildren,
  HomeDashboardRoute: HomeDashboardRoute,
  HomeEmployeeRoute: HomeEmployeeRouteWithChildren,
  HomeInventoryHistoryRoute: HomeInventoryHistoryRoute,
  HomeInventoryManagementRoute: HomeInventoryManagementRoute,
  HomeMenuManagementRoute: HomeMenuManagementRoute,
  HomeNotificationsRoute: HomeNotificationsRouteWithChildren,
  HomePayLaterCustomersRoute: HomePayLaterCustomersRouteWithChildren,
  HomeTakeOrderRoute: HomeTakeOrderRoute,
  HomeVendorsRoute: HomeVendorsRouteWithChildren,
  HomeBillingLazyRoute: HomeBillingLazyRoute,
  HomeCalendarLazyRoute: HomeCalendarLazyRoute,
  HomeConfigurationsLazyRoute: HomeConfigurationsLazyRoute,
  HomeHelpLazyRoute: HomeHelpLazyRoute,
  HomePrinterConfigLazyRoute: HomePrinterConfigLazyRoute,
  HomeSettingsLazyRoute: HomeSettingsLazyRoute,
}

const HomeRouteWithChildren = HomeRoute._addFileChildren(HomeRouteChildren)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/home': typeof HomeRouteWithChildren
  '/unverified': typeof UnverifiedRoute
  '/printerConfig': typeof PrinterConfigLazyRoute
  '/home/assets': typeof HomeAssetsRouteRouteWithChildren
  '/home/expenseLedger': typeof HomeExpenseLedgerRouteRouteWithChildren
  '/home/dashboard': typeof HomeDashboardRoute
  '/home/employee': typeof HomeEmployeeRouteWithChildren
  '/home/inventoryHistory': typeof HomeInventoryHistoryRoute
  '/home/inventoryManagement': typeof HomeInventoryManagementRoute
  '/home/menuManagement': typeof HomeMenuManagementRoute
  '/home/notifications': typeof HomeNotificationsRouteWithChildren
  '/home/payLaterCustomers': typeof HomePayLaterCustomersRouteWithChildren
  '/home/takeOrder': typeof HomeTakeOrderRoute
  '/home/vendors': typeof HomeVendorsRouteWithChildren
  '/home/billing': typeof HomeBillingLazyRoute
  '/home/calendar': typeof HomeCalendarLazyRoute
  '/home/configurations': typeof HomeConfigurationsLazyRoute
  '/home/help': typeof HomeHelpLazyRoute
  '/home/printerConfig': typeof HomePrinterConfigLazyRoute
  '/home/settings': typeof HomeSettingsLazyRoute
  '/home/assets/$department': typeof HomeAssetsDepartmentRoute
  '/home/employee/$salaryLedger': typeof HomeEmployeeSalaryLedgerRoute
  '/home/employee/employeeDailyReport': typeof HomeEmployeeEmployeeDailyReportRouteWithChildren
  '/home/employee/table': typeof HomeEmployeeTableRoute
  '/home/expenseLedger/$department': typeof HomeExpenseLedgerDepartmentRoute
  '/home/notifications/orderNotification': typeof HomeNotificationsOrderNotificationRoute
  '/home/payLaterCustomers/$id': typeof HomePayLaterCustomersIdRoute
  '/home/payLaterCustomers/payLaterCustomersAll': typeof HomePayLaterCustomersPayLaterCustomersAllRoute
  '/home/vendors/$id': typeof HomeVendorsIdRoute
  '/home/vendors/vendorsAll': typeof HomeVendorsVendorsAllRoute
  '/home/employee/employeeDailyReport/$employeeId': typeof HomeEmployeeEmployeeDailyReportEmployeeIdRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/home': typeof HomeRouteWithChildren
  '/unverified': typeof UnverifiedRoute
  '/printerConfig': typeof PrinterConfigLazyRoute
  '/home/assets': typeof HomeAssetsRouteRouteWithChildren
  '/home/expenseLedger': typeof HomeExpenseLedgerRouteRouteWithChildren
  '/home/dashboard': typeof HomeDashboardRoute
  '/home/employee': typeof HomeEmployeeRouteWithChildren
  '/home/inventoryHistory': typeof HomeInventoryHistoryRoute
  '/home/inventoryManagement': typeof HomeInventoryManagementRoute
  '/home/menuManagement': typeof HomeMenuManagementRoute
  '/home/notifications': typeof HomeNotificationsRouteWithChildren
  '/home/payLaterCustomers': typeof HomePayLaterCustomersRouteWithChildren
  '/home/takeOrder': typeof HomeTakeOrderRoute
  '/home/vendors': typeof HomeVendorsRouteWithChildren
  '/home/billing': typeof HomeBillingLazyRoute
  '/home/calendar': typeof HomeCalendarLazyRoute
  '/home/configurations': typeof HomeConfigurationsLazyRoute
  '/home/help': typeof HomeHelpLazyRoute
  '/home/printerConfig': typeof HomePrinterConfigLazyRoute
  '/home/settings': typeof HomeSettingsLazyRoute
  '/home/assets/$department': typeof HomeAssetsDepartmentRoute
  '/home/employee/$salaryLedger': typeof HomeEmployeeSalaryLedgerRoute
  '/home/employee/employeeDailyReport': typeof HomeEmployeeEmployeeDailyReportRouteWithChildren
  '/home/employee/table': typeof HomeEmployeeTableRoute
  '/home/expenseLedger/$department': typeof HomeExpenseLedgerDepartmentRoute
  '/home/notifications/orderNotification': typeof HomeNotificationsOrderNotificationRoute
  '/home/payLaterCustomers/$id': typeof HomePayLaterCustomersIdRoute
  '/home/payLaterCustomers/payLaterCustomersAll': typeof HomePayLaterCustomersPayLaterCustomersAllRoute
  '/home/vendors/$id': typeof HomeVendorsIdRoute
  '/home/vendors/vendorsAll': typeof HomeVendorsVendorsAllRoute
  '/home/employee/employeeDailyReport/$employeeId': typeof HomeEmployeeEmployeeDailyReportEmployeeIdRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/home': typeof HomeRouteWithChildren
  '/unverified': typeof UnverifiedRoute
  '/printerConfig': typeof PrinterConfigLazyRoute
  '/home/assets': typeof HomeAssetsRouteRouteWithChildren
  '/home/expenseLedger': typeof HomeExpenseLedgerRouteRouteWithChildren
  '/home/dashboard': typeof HomeDashboardRoute
  '/home/employee': typeof HomeEmployeeRouteWithChildren
  '/home/inventoryHistory': typeof HomeInventoryHistoryRoute
  '/home/inventoryManagement': typeof HomeInventoryManagementRoute
  '/home/menuManagement': typeof HomeMenuManagementRoute
  '/home/notifications': typeof HomeNotificationsRouteWithChildren
  '/home/payLaterCustomers': typeof HomePayLaterCustomersRouteWithChildren
  '/home/takeOrder': typeof HomeTakeOrderRoute
  '/home/vendors': typeof HomeVendorsRouteWithChildren
  '/home/billing': typeof HomeBillingLazyRoute
  '/home/calendar': typeof HomeCalendarLazyRoute
  '/home/configurations': typeof HomeConfigurationsLazyRoute
  '/home/help': typeof HomeHelpLazyRoute
  '/home/printerConfig': typeof HomePrinterConfigLazyRoute
  '/home/settings': typeof HomeSettingsLazyRoute
  '/home/assets/$department': typeof HomeAssetsDepartmentRoute
  '/home/employee/$salaryLedger': typeof HomeEmployeeSalaryLedgerRoute
  '/home/employee/employeeDailyReport': typeof HomeEmployeeEmployeeDailyReportRouteWithChildren
  '/home/employee/table': typeof HomeEmployeeTableRoute
  '/home/expenseLedger/$department': typeof HomeExpenseLedgerDepartmentRoute
  '/home/notifications/orderNotification': typeof HomeNotificationsOrderNotificationRoute
  '/home/payLaterCustomers/$id': typeof HomePayLaterCustomersIdRoute
  '/home/payLaterCustomers/payLaterCustomersAll': typeof HomePayLaterCustomersPayLaterCustomersAllRoute
  '/home/vendors/$id': typeof HomeVendorsIdRoute
  '/home/vendors/vendorsAll': typeof HomeVendorsVendorsAllRoute
  '/home/employee/employeeDailyReport/$employeeId': typeof HomeEmployeeEmployeeDailyReportEmployeeIdRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/home'
    | '/unverified'
    | '/printerConfig'
    | '/home/assets'
    | '/home/expenseLedger'
    | '/home/dashboard'
    | '/home/employee'
    | '/home/inventoryHistory'
    | '/home/inventoryManagement'
    | '/home/menuManagement'
    | '/home/notifications'
    | '/home/payLaterCustomers'
    | '/home/takeOrder'
    | '/home/vendors'
    | '/home/billing'
    | '/home/calendar'
    | '/home/configurations'
    | '/home/help'
    | '/home/printerConfig'
    | '/home/settings'
    | '/home/assets/$department'
    | '/home/employee/$salaryLedger'
    | '/home/employee/employeeDailyReport'
    | '/home/employee/table'
    | '/home/expenseLedger/$department'
    | '/home/notifications/orderNotification'
    | '/home/payLaterCustomers/$id'
    | '/home/payLaterCustomers/payLaterCustomersAll'
    | '/home/vendors/$id'
    | '/home/vendors/vendorsAll'
    | '/home/employee/employeeDailyReport/$employeeId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/home'
    | '/unverified'
    | '/printerConfig'
    | '/home/assets'
    | '/home/expenseLedger'
    | '/home/dashboard'
    | '/home/employee'
    | '/home/inventoryHistory'
    | '/home/inventoryManagement'
    | '/home/menuManagement'
    | '/home/notifications'
    | '/home/payLaterCustomers'
    | '/home/takeOrder'
    | '/home/vendors'
    | '/home/billing'
    | '/home/calendar'
    | '/home/configurations'
    | '/home/help'
    | '/home/printerConfig'
    | '/home/settings'
    | '/home/assets/$department'
    | '/home/employee/$salaryLedger'
    | '/home/employee/employeeDailyReport'
    | '/home/employee/table'
    | '/home/expenseLedger/$department'
    | '/home/notifications/orderNotification'
    | '/home/payLaterCustomers/$id'
    | '/home/payLaterCustomers/payLaterCustomersAll'
    | '/home/vendors/$id'
    | '/home/vendors/vendorsAll'
    | '/home/employee/employeeDailyReport/$employeeId'
  id:
    | '__root__'
    | '/'
    | '/home'
    | '/unverified'
    | '/printerConfig'
    | '/home/assets'
    | '/home/expenseLedger'
    | '/home/dashboard'
    | '/home/employee'
    | '/home/inventoryHistory'
    | '/home/inventoryManagement'
    | '/home/menuManagement'
    | '/home/notifications'
    | '/home/payLaterCustomers'
    | '/home/takeOrder'
    | '/home/vendors'
    | '/home/billing'
    | '/home/calendar'
    | '/home/configurations'
    | '/home/help'
    | '/home/printerConfig'
    | '/home/settings'
    | '/home/assets/$department'
    | '/home/employee/$salaryLedger'
    | '/home/employee/employeeDailyReport'
    | '/home/employee/table'
    | '/home/expenseLedger/$department'
    | '/home/notifications/orderNotification'
    | '/home/payLaterCustomers/$id'
    | '/home/payLaterCustomers/payLaterCustomersAll'
    | '/home/vendors/$id'
    | '/home/vendors/vendorsAll'
    | '/home/employee/employeeDailyReport/$employeeId'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  HomeRoute: typeof HomeRouteWithChildren
  UnverifiedRoute: typeof UnverifiedRoute
  PrinterConfigLazyRoute: typeof PrinterConfigLazyRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  HomeRoute: HomeRouteWithChildren,
  UnverifiedRoute: UnverifiedRoute,
  PrinterConfigLazyRoute: PrinterConfigLazyRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/home",
        "/unverified",
        "/printerConfig"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/home": {
      "filePath": "home.tsx",
      "children": [
        "/home/assets",
        "/home/expenseLedger",
        "/home/dashboard",
        "/home/employee",
        "/home/inventoryHistory",
        "/home/inventoryManagement",
        "/home/menuManagement",
        "/home/notifications",
        "/home/payLaterCustomers",
        "/home/takeOrder",
        "/home/vendors",
        "/home/billing",
        "/home/calendar",
        "/home/configurations",
        "/home/help",
        "/home/printerConfig",
        "/home/settings"
      ]
    },
    "/unverified": {
      "filePath": "unverified.tsx"
    },
    "/printerConfig": {
      "filePath": "printerConfig.lazy.tsx"
    },
    "/home/assets": {
      "filePath": "home/assets/route.tsx",
      "parent": "/home",
      "children": [
        "/home/assets/$department"
      ]
    },
    "/home/expenseLedger": {
      "filePath": "home/expenseLedger/route.tsx",
      "parent": "/home",
      "children": [
        "/home/expenseLedger/$department"
      ]
    },
    "/home/dashboard": {
      "filePath": "home/dashboard.tsx",
      "parent": "/home"
    },
    "/home/employee": {
      "filePath": "home/employee.tsx",
      "parent": "/home",
      "children": [
        "/home/employee/$salaryLedger",
        "/home/employee/employeeDailyReport",
        "/home/employee/table"
      ]
    },
    "/home/inventoryHistory": {
      "filePath": "home/inventoryHistory.tsx",
      "parent": "/home"
    },
    "/home/inventoryManagement": {
      "filePath": "home/inventoryManagement.tsx",
      "parent": "/home"
    },
    "/home/menuManagement": {
      "filePath": "home/menuManagement.tsx",
      "parent": "/home"
    },
    "/home/notifications": {
      "filePath": "home/notifications.tsx",
      "parent": "/home",
      "children": [
        "/home/notifications/orderNotification"
      ]
    },
    "/home/payLaterCustomers": {
      "filePath": "home/payLaterCustomers.tsx",
      "parent": "/home",
      "children": [
        "/home/payLaterCustomers/$id",
        "/home/payLaterCustomers/payLaterCustomersAll"
      ]
    },
    "/home/takeOrder": {
      "filePath": "home/takeOrder.tsx",
      "parent": "/home"
    },
    "/home/vendors": {
      "filePath": "home/vendors.tsx",
      "parent": "/home",
      "children": [
        "/home/vendors/$id",
        "/home/vendors/vendorsAll"
      ]
    },
    "/home/billing": {
      "filePath": "home/billing.lazy.tsx",
      "parent": "/home"
    },
    "/home/calendar": {
      "filePath": "home/calendar.lazy.tsx",
      "parent": "/home"
    },
    "/home/configurations": {
      "filePath": "home/configurations.lazy.tsx",
      "parent": "/home"
    },
    "/home/help": {
      "filePath": "home/help.lazy.tsx",
      "parent": "/home"
    },
    "/home/printerConfig": {
      "filePath": "home/printerConfig.lazy.tsx",
      "parent": "/home"
    },
    "/home/settings": {
      "filePath": "home/settings.lazy.tsx",
      "parent": "/home"
    },
    "/home/assets/$department": {
      "filePath": "home/assets/$department.tsx",
      "parent": "/home/assets"
    },
    "/home/employee/$salaryLedger": {
      "filePath": "home/employee/$salaryLedger.tsx",
      "parent": "/home/employee"
    },
    "/home/employee/employeeDailyReport": {
      "filePath": "home/employee/employeeDailyReport.tsx",
      "parent": "/home/employee",
      "children": [
        "/home/employee/employeeDailyReport/$employeeId"
      ]
    },
    "/home/employee/table": {
      "filePath": "home/employee/table.tsx",
      "parent": "/home/employee"
    },
    "/home/expenseLedger/$department": {
      "filePath": "home/expenseLedger/$department.tsx",
      "parent": "/home/expenseLedger"
    },
    "/home/notifications/orderNotification": {
      "filePath": "home/notifications/orderNotification.tsx",
      "parent": "/home/notifications"
    },
    "/home/payLaterCustomers/$id": {
      "filePath": "home/payLaterCustomers/$id.tsx",
      "parent": "/home/payLaterCustomers"
    },
    "/home/payLaterCustomers/payLaterCustomersAll": {
      "filePath": "home/payLaterCustomers/payLaterCustomersAll.tsx",
      "parent": "/home/payLaterCustomers"
    },
    "/home/vendors/$id": {
      "filePath": "home/vendors/$id.tsx",
      "parent": "/home/vendors"
    },
    "/home/vendors/vendorsAll": {
      "filePath": "home/vendors/vendorsAll.tsx",
      "parent": "/home/vendors"
    },
    "/home/employee/employeeDailyReport/$employeeId": {
      "filePath": "home/employee/employeeDailyReport/$employeeId.tsx",
      "parent": "/home/employee/employeeDailyReport"
    }
  }
}
ROUTE_MANIFEST_END */
