/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as ProfileCompleteImport } from './routes/profileComplete'
import { Route as HomeImport } from './routes/home'
import { Route as AboutImport } from './routes/about'
import { Route as IndexImport } from './routes/index'
import { Route as HomeStockImport } from './routes/home/stock'
import { Route as HomeNotificationsImport } from './routes/home/notifications'
import { Route as HomeLedgersImport } from './routes/home/ledgers'
import { Route as HomeEmployeeImport } from './routes/home/employee'
import { Route as HomeEditMenuImport } from './routes/home/editMenu'
import { Route as HomeDashboardImport } from './routes/home/dashboard'
import { Route as HomeCreditorsImport } from './routes/home/creditors'
import { Route as HomeBillingImport } from './routes/home/billing'
import { Route as HomeNicknameImport } from './routes/home/$nickname'
import { Route as HomeNotificationsStockNotificationImport } from './routes/home/notifications/stockNotification'
import { Route as HomeNotificationsOrderNotificationImport } from './routes/home/notifications/orderNotification'

// Create Virtual Routes

const HomeSettingsLazyImport = createFileRoute('/home/settings')()
const HomeHelpLazyImport = createFileRoute('/home/help')()
const HomeCalendarLazyImport = createFileRoute('/home/calendar')()
const HomeAccountLazyImport = createFileRoute('/home/account')()

// Create/Update Routes

const ProfileCompleteRoute = ProfileCompleteImport.update({
  id: '/profileComplete',
  path: '/profileComplete',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/profileComplete.lazy').then((d) => d.Route),
)

const HomeRoute = HomeImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRoute,
} as any)

const AboutRoute = AboutImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const HomeSettingsLazyRoute = HomeSettingsLazyImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => HomeRoute,
} as any).lazy(() => import('./routes/home/settings.lazy').then((d) => d.Route))

const HomeHelpLazyRoute = HomeHelpLazyImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => HomeRoute,
} as any).lazy(() => import('./routes/home/help.lazy').then((d) => d.Route))

const HomeCalendarLazyRoute = HomeCalendarLazyImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => HomeRoute,
} as any).lazy(() => import('./routes/home/calendar.lazy').then((d) => d.Route))

const HomeAccountLazyRoute = HomeAccountLazyImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => HomeRoute,
} as any).lazy(() => import('./routes/home/account.lazy').then((d) => d.Route))

const HomeStockRoute = HomeStockImport.update({
  id: '/stock',
  path: '/stock',
  getParentRoute: () => HomeRoute,
} as any).lazy(() => import('./routes/home/stock.lazy').then((d) => d.Route))

const HomeNotificationsRoute = HomeNotificationsImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => HomeRoute,
} as any)

const HomeLedgersRoute = HomeLedgersImport.update({
  id: '/ledgers',
  path: '/ledgers',
  getParentRoute: () => HomeRoute,
} as any)

const HomeEmployeeRoute = HomeEmployeeImport.update({
  id: '/employee',
  path: '/employee',
  getParentRoute: () => HomeRoute,
} as any).lazy(() => import('./routes/home/employee.lazy').then((d) => d.Route))

const HomeEditMenuRoute = HomeEditMenuImport.update({
  id: '/editMenu',
  path: '/editMenu',
  getParentRoute: () => HomeRoute,
} as any)

const HomeDashboardRoute = HomeDashboardImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => HomeRoute,
} as any).lazy(() =>
  import('./routes/home/dashboard.lazy').then((d) => d.Route),
)

const HomeCreditorsRoute = HomeCreditorsImport.update({
  id: '/creditors',
  path: '/creditors',
  getParentRoute: () => HomeRoute,
} as any)

const HomeBillingRoute = HomeBillingImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => HomeRoute,
} as any).lazy(() => import('./routes/home/billing.lazy').then((d) => d.Route))

const HomeNicknameRoute = HomeNicknameImport.update({
  id: '/$nickname',
  path: '/$nickname',
  getParentRoute: () => HomeRoute,
} as any)

const HomeNotificationsStockNotificationRoute =
  HomeNotificationsStockNotificationImport.update({
    id: '/stockNotification',
    path: '/stockNotification',
    getParentRoute: () => HomeNotificationsRoute,
  } as any)

const HomeNotificationsOrderNotificationRoute =
  HomeNotificationsOrderNotificationImport.update({
    id: '/orderNotification',
    path: '/orderNotification',
    getParentRoute: () => HomeNotificationsRoute,
  } as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutImport
      parentRoute: typeof rootRoute
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeImport
      parentRoute: typeof rootRoute
    }
    '/profileComplete': {
      id: '/profileComplete'
      path: '/profileComplete'
      fullPath: '/profileComplete'
      preLoaderRoute: typeof ProfileCompleteImport
      parentRoute: typeof rootRoute
    }
    '/home/$nickname': {
      id: '/home/$nickname'
      path: '/$nickname'
      fullPath: '/home/$nickname'
      preLoaderRoute: typeof HomeNicknameImport
      parentRoute: typeof HomeImport
    }
    '/home/billing': {
      id: '/home/billing'
      path: '/billing'
      fullPath: '/home/billing'
      preLoaderRoute: typeof HomeBillingImport
      parentRoute: typeof HomeImport
    }
    '/home/creditors': {
      id: '/home/creditors'
      path: '/creditors'
      fullPath: '/home/creditors'
      preLoaderRoute: typeof HomeCreditorsImport
      parentRoute: typeof HomeImport
    }
    '/home/dashboard': {
      id: '/home/dashboard'
      path: '/dashboard'
      fullPath: '/home/dashboard'
      preLoaderRoute: typeof HomeDashboardImport
      parentRoute: typeof HomeImport
    }
    '/home/editMenu': {
      id: '/home/editMenu'
      path: '/editMenu'
      fullPath: '/home/editMenu'
      preLoaderRoute: typeof HomeEditMenuImport
      parentRoute: typeof HomeImport
    }
    '/home/employee': {
      id: '/home/employee'
      path: '/employee'
      fullPath: '/home/employee'
      preLoaderRoute: typeof HomeEmployeeImport
      parentRoute: typeof HomeImport
    }
    '/home/ledgers': {
      id: '/home/ledgers'
      path: '/ledgers'
      fullPath: '/home/ledgers'
      preLoaderRoute: typeof HomeLedgersImport
      parentRoute: typeof HomeImport
    }
    '/home/notifications': {
      id: '/home/notifications'
      path: '/notifications'
      fullPath: '/home/notifications'
      preLoaderRoute: typeof HomeNotificationsImport
      parentRoute: typeof HomeImport
    }
    '/home/stock': {
      id: '/home/stock'
      path: '/stock'
      fullPath: '/home/stock'
      preLoaderRoute: typeof HomeStockImport
      parentRoute: typeof HomeImport
    }
    '/home/account': {
      id: '/home/account'
      path: '/account'
      fullPath: '/home/account'
      preLoaderRoute: typeof HomeAccountLazyImport
      parentRoute: typeof HomeImport
    }
    '/home/calendar': {
      id: '/home/calendar'
      path: '/calendar'
      fullPath: '/home/calendar'
      preLoaderRoute: typeof HomeCalendarLazyImport
      parentRoute: typeof HomeImport
    }
    '/home/help': {
      id: '/home/help'
      path: '/help'
      fullPath: '/home/help'
      preLoaderRoute: typeof HomeHelpLazyImport
      parentRoute: typeof HomeImport
    }
    '/home/settings': {
      id: '/home/settings'
      path: '/settings'
      fullPath: '/home/settings'
      preLoaderRoute: typeof HomeSettingsLazyImport
      parentRoute: typeof HomeImport
    }
    '/home/notifications/orderNotification': {
      id: '/home/notifications/orderNotification'
      path: '/orderNotification'
      fullPath: '/home/notifications/orderNotification'
      preLoaderRoute: typeof HomeNotificationsOrderNotificationImport
      parentRoute: typeof HomeNotificationsImport
    }
    '/home/notifications/stockNotification': {
      id: '/home/notifications/stockNotification'
      path: '/stockNotification'
      fullPath: '/home/notifications/stockNotification'
      preLoaderRoute: typeof HomeNotificationsStockNotificationImport
      parentRoute: typeof HomeNotificationsImport
    }
  }
}

// Create and export the route tree

interface HomeNotificationsRouteChildren {
  HomeNotificationsOrderNotificationRoute: typeof HomeNotificationsOrderNotificationRoute
  HomeNotificationsStockNotificationRoute: typeof HomeNotificationsStockNotificationRoute
}

const HomeNotificationsRouteChildren: HomeNotificationsRouteChildren = {
  HomeNotificationsOrderNotificationRoute:
    HomeNotificationsOrderNotificationRoute,
  HomeNotificationsStockNotificationRoute:
    HomeNotificationsStockNotificationRoute,
}

const HomeNotificationsRouteWithChildren =
  HomeNotificationsRoute._addFileChildren(HomeNotificationsRouteChildren)

interface HomeRouteChildren {
  HomeNicknameRoute: typeof HomeNicknameRoute
  HomeBillingRoute: typeof HomeBillingRoute
  HomeCreditorsRoute: typeof HomeCreditorsRoute
  HomeDashboardRoute: typeof HomeDashboardRoute
  HomeEditMenuRoute: typeof HomeEditMenuRoute
  HomeEmployeeRoute: typeof HomeEmployeeRoute
  HomeLedgersRoute: typeof HomeLedgersRoute
  HomeNotificationsRoute: typeof HomeNotificationsRouteWithChildren
  HomeStockRoute: typeof HomeStockRoute
  HomeAccountLazyRoute: typeof HomeAccountLazyRoute
  HomeCalendarLazyRoute: typeof HomeCalendarLazyRoute
  HomeHelpLazyRoute: typeof HomeHelpLazyRoute
  HomeSettingsLazyRoute: typeof HomeSettingsLazyRoute
}

const HomeRouteChildren: HomeRouteChildren = {
  HomeNicknameRoute: HomeNicknameRoute,
  HomeBillingRoute: HomeBillingRoute,
  HomeCreditorsRoute: HomeCreditorsRoute,
  HomeDashboardRoute: HomeDashboardRoute,
  HomeEditMenuRoute: HomeEditMenuRoute,
  HomeEmployeeRoute: HomeEmployeeRoute,
  HomeLedgersRoute: HomeLedgersRoute,
  HomeNotificationsRoute: HomeNotificationsRouteWithChildren,
  HomeStockRoute: HomeStockRoute,
  HomeAccountLazyRoute: HomeAccountLazyRoute,
  HomeCalendarLazyRoute: HomeCalendarLazyRoute,
  HomeHelpLazyRoute: HomeHelpLazyRoute,
  HomeSettingsLazyRoute: HomeSettingsLazyRoute,
}

const HomeRouteWithChildren = HomeRoute._addFileChildren(HomeRouteChildren)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/home': typeof HomeRouteWithChildren
  '/profileComplete': typeof ProfileCompleteRoute
  '/home/$nickname': typeof HomeNicknameRoute
  '/home/billing': typeof HomeBillingRoute
  '/home/creditors': typeof HomeCreditorsRoute
  '/home/dashboard': typeof HomeDashboardRoute
  '/home/editMenu': typeof HomeEditMenuRoute
  '/home/employee': typeof HomeEmployeeRoute
  '/home/ledgers': typeof HomeLedgersRoute
  '/home/notifications': typeof HomeNotificationsRouteWithChildren
  '/home/stock': typeof HomeStockRoute
  '/home/account': typeof HomeAccountLazyRoute
  '/home/calendar': typeof HomeCalendarLazyRoute
  '/home/help': typeof HomeHelpLazyRoute
  '/home/settings': typeof HomeSettingsLazyRoute
  '/home/notifications/orderNotification': typeof HomeNotificationsOrderNotificationRoute
  '/home/notifications/stockNotification': typeof HomeNotificationsStockNotificationRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/home': typeof HomeRouteWithChildren
  '/profileComplete': typeof ProfileCompleteRoute
  '/home/$nickname': typeof HomeNicknameRoute
  '/home/billing': typeof HomeBillingRoute
  '/home/creditors': typeof HomeCreditorsRoute
  '/home/dashboard': typeof HomeDashboardRoute
  '/home/editMenu': typeof HomeEditMenuRoute
  '/home/employee': typeof HomeEmployeeRoute
  '/home/ledgers': typeof HomeLedgersRoute
  '/home/notifications': typeof HomeNotificationsRouteWithChildren
  '/home/stock': typeof HomeStockRoute
  '/home/account': typeof HomeAccountLazyRoute
  '/home/calendar': typeof HomeCalendarLazyRoute
  '/home/help': typeof HomeHelpLazyRoute
  '/home/settings': typeof HomeSettingsLazyRoute
  '/home/notifications/orderNotification': typeof HomeNotificationsOrderNotificationRoute
  '/home/notifications/stockNotification': typeof HomeNotificationsStockNotificationRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/home': typeof HomeRouteWithChildren
  '/profileComplete': typeof ProfileCompleteRoute
  '/home/$nickname': typeof HomeNicknameRoute
  '/home/billing': typeof HomeBillingRoute
  '/home/creditors': typeof HomeCreditorsRoute
  '/home/dashboard': typeof HomeDashboardRoute
  '/home/editMenu': typeof HomeEditMenuRoute
  '/home/employee': typeof HomeEmployeeRoute
  '/home/ledgers': typeof HomeLedgersRoute
  '/home/notifications': typeof HomeNotificationsRouteWithChildren
  '/home/stock': typeof HomeStockRoute
  '/home/account': typeof HomeAccountLazyRoute
  '/home/calendar': typeof HomeCalendarLazyRoute
  '/home/help': typeof HomeHelpLazyRoute
  '/home/settings': typeof HomeSettingsLazyRoute
  '/home/notifications/orderNotification': typeof HomeNotificationsOrderNotificationRoute
  '/home/notifications/stockNotification': typeof HomeNotificationsStockNotificationRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/home'
    | '/profileComplete'
    | '/home/$nickname'
    | '/home/billing'
    | '/home/creditors'
    | '/home/dashboard'
    | '/home/editMenu'
    | '/home/employee'
    | '/home/ledgers'
    | '/home/notifications'
    | '/home/stock'
    | '/home/account'
    | '/home/calendar'
    | '/home/help'
    | '/home/settings'
    | '/home/notifications/orderNotification'
    | '/home/notifications/stockNotification'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/home'
    | '/profileComplete'
    | '/home/$nickname'
    | '/home/billing'
    | '/home/creditors'
    | '/home/dashboard'
    | '/home/editMenu'
    | '/home/employee'
    | '/home/ledgers'
    | '/home/notifications'
    | '/home/stock'
    | '/home/account'
    | '/home/calendar'
    | '/home/help'
    | '/home/settings'
    | '/home/notifications/orderNotification'
    | '/home/notifications/stockNotification'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/home'
    | '/profileComplete'
    | '/home/$nickname'
    | '/home/billing'
    | '/home/creditors'
    | '/home/dashboard'
    | '/home/editMenu'
    | '/home/employee'
    | '/home/ledgers'
    | '/home/notifications'
    | '/home/stock'
    | '/home/account'
    | '/home/calendar'
    | '/home/help'
    | '/home/settings'
    | '/home/notifications/orderNotification'
    | '/home/notifications/stockNotification'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  HomeRoute: typeof HomeRouteWithChildren
  ProfileCompleteRoute: typeof ProfileCompleteRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  HomeRoute: HomeRouteWithChildren,
  ProfileCompleteRoute: ProfileCompleteRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/about",
        "/home",
        "/profileComplete"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/about": {
      "filePath": "about.tsx"
    },
    "/home": {
      "filePath": "home.tsx",
      "children": [
        "/home/$nickname",
        "/home/billing",
        "/home/creditors",
        "/home/dashboard",
        "/home/editMenu",
        "/home/employee",
        "/home/ledgers",
        "/home/notifications",
        "/home/stock",
        "/home/account",
        "/home/calendar",
        "/home/help",
        "/home/settings"
      ]
    },
    "/profileComplete": {
      "filePath": "profileComplete.tsx"
    },
    "/home/$nickname": {
      "filePath": "home/$nickname.tsx",
      "parent": "/home"
    },
    "/home/billing": {
      "filePath": "home/billing.tsx",
      "parent": "/home"
    },
    "/home/creditors": {
      "filePath": "home/creditors.tsx",
      "parent": "/home"
    },
    "/home/dashboard": {
      "filePath": "home/dashboard.tsx",
      "parent": "/home"
    },
    "/home/editMenu": {
      "filePath": "home/editMenu.tsx",
      "parent": "/home"
    },
    "/home/employee": {
      "filePath": "home/employee.tsx",
      "parent": "/home"
    },
    "/home/ledgers": {
      "filePath": "home/ledgers.tsx",
      "parent": "/home"
    },
    "/home/notifications": {
      "filePath": "home/notifications.tsx",
      "parent": "/home",
      "children": [
        "/home/notifications/orderNotification",
        "/home/notifications/stockNotification"
      ]
    },
    "/home/stock": {
      "filePath": "home/stock.tsx",
      "parent": "/home"
    },
    "/home/account": {
      "filePath": "home/account.lazy.tsx",
      "parent": "/home"
    },
    "/home/calendar": {
      "filePath": "home/calendar.lazy.tsx",
      "parent": "/home"
    },
    "/home/help": {
      "filePath": "home/help.lazy.tsx",
      "parent": "/home"
    },
    "/home/settings": {
      "filePath": "home/settings.lazy.tsx",
      "parent": "/home"
    },
    "/home/notifications/orderNotification": {
      "filePath": "home/notifications/orderNotification.tsx",
      "parent": "/home/notifications"
    },
    "/home/notifications/stockNotification": {
      "filePath": "home/notifications/stockNotification.tsx",
      "parent": "/home/notifications"
    }
  }
}
ROUTE_MANIFEST_END */
